"""Add gender to user and female preference to ride

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2026-04-16 01:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=10), server_default='other', nullable=True))
    op.add_column('rides', sa.Column('prefer_female_driver', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'prefer_female_driver')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
